import { authProtectedRoutes } from "./routes"

const sharedRole = [
  authProtectedRoutes?.addBrand,
  authProtectedRoutes?.addProduct,
  authProtectedRoutes?.products,
  authProtectedRoutes?.brand,
  authProtectedRoutes?.stocks,
  authProtectedRoutes?.addCategory,
  authProtectedRoutes?.addColor,
  authProtectedRoutes?.addSize,
  authProtectedRoutes?.color,
  authProtectedRoutes?.category,
  authProtectedRoutes?.size,
  authProtectedRoutes?.productFeatures,
  authProtectedRoutes?.addSale,
  authProtectedRoutes?.addOffer,
  authProtectedRoutes?.addCollection,
  authProtectedRoutes?.collection,
  authProtectedRoutes?.offers,
  authProtectedRoutes?.sale,
  authProtectedRoutes?.addChart,
  authProtectedRoutes?.addChartContent,
  authProtectedRoutes?.addChartData,
  authProtectedRoutes?.chart,
  authProtectedRoutes?.chartContent,
  authProtectedRoutes?.chartData,
  authProtectedRoutes?.addBulkAlert,
  authProtectedRoutes?.addNews,
  authProtectedRoutes?.addNewsletter,
  authProtectedRoutes?.bulkAlert,
  authProtectedRoutes?.news,
  authProtectedRoutes?.newsletter,
  authProtectedRoutes?.newsletterSubscription,
  authProtectedRoutes?.addOrderStatus,
  authProtectedRoutes?.addReturnStatus,
  authProtectedRoutes?.addWarehouse,
  authProtectedRoutes?.addWarehouseAvailability,
  authProtectedRoutes?.orders,
  authProtectedRoutes?.orderReturnRequest,
  authProtectedRoutes?.orderStatus,
  authProtectedRoutes?.returnStatus,
  authProtectedRoutes?.warehouses,
  authProtectedRoutes?.warehouseAvailability,
  authProtectedRoutes?.addPoint,
  authProtectedRoutes?.addCoupon,
  authProtectedRoutes?.coupons,
  authProtectedRoutes?.points,
  authProtectedRoutes?.homeReviews,
  authProtectedRoutes?.addReview,
  authProtectedRoutes?.comments,
  authProtectedRoutes?.users,
  authProtectedRoutes?.addUser,
  authProtectedRoutes?.singleUser,
  authProtectedRoutes?.singleUserInfo,
  authProtectedRoutes?.update,
  authProtectedRoutes?.logs,
  authProtectedRoutes?.addBrand,
  authProtectedRoutes?.addBulkAlert,
  authProtectedRoutes?.selectProducts,
  authProtectedRoutes?.uploadSheet,
  authProtectedRoutes?.sendEmail,
  authProtectedRoutes?.homeSections,
  authProtectedRoutes?.home,
  authProtectedRoutes?.notAllowed,
  authProtectedRoutes?.notFound,
]

const admin = [
  ...sharedRole,
  authProtectedRoutes?.addCountry,
  authProtectedRoutes?.addCurrency,
  authProtectedRoutes?.addLanguage,
  authProtectedRoutes?.addRegion,
  authProtectedRoutes?.address,
  authProtectedRoutes?.country,
  authProtectedRoutes?.region,
  authProtectedRoutes?.currency,
]

export const PERMISSIONS = {
  admin,
  superadmin: sharedRole,
  modrator: sharedRole
}

export const SUPERADMIN_PERMISSIONS = [
  'user_table',
  'user_address',
  'user_wallet',
  'user_point',
  'user_type',
  'user',
  'user_cart',
  'user_alert',
  'user_invite',
  'user_like',
  'user_suggestion',
  'user_ticket',
  "order",
  "order_return_request"
]