const { DropDowns } = require("../functions");

export const ContractType = [
  // {
  //   required: false,
  //   label: "Number",
  //   name: "number",
  //   type: "number",
  // },
  {
    required: false,
    label: "Guid",
    name: "guid",
    type: "text",
  },
  {
    required: false,
    label: "SecLvl",
    name: "seclvl",
    key: "select",
    list: DropDowns("SecLvl"),
  },
  {
    required: false,
    label: "Code",
    name: "code",
    type: "text",
  },
  {
    required: true,
    label: "Name",
    name: "name",
    type: "text",
  },
  {
    required: false,
    label: "ltnName",
    name: "ltnname",
    type: "text",
  },
  {
    required: false,
    label: "Menu",
    name: "menu",
    type: "text",
  },
  {
    required: false,
    label: "LtnMenu",
    name: "ltnmenu",
    type: "text",
  },
  {
    required: false,
    label: "ShortCut",
    name: "shortcut",
    type: "text",
  },
  {
    required: false,
    label: "ContractKind",
    name: "contractkind",
    key: "select",
    list: DropDowns("ContractKind"),
  },
  {
    required: false,
    label: "IsAutoRenewal",
    name: "isautorenewal",
    type: "checkbox",
  },
  {
    required: false,
    label: "RevenueAccountGUID",
    name: "revenueaccountguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "AcCommissionFromCustGUID",
    name: "accommissionfromcustguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "AcCommissionFromOwnerGUID",
    name: "accommissionfromownerguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "AccountContractPriceGUID",
    name: "accountcontractpriceguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "AccountCertificatValueGUID",
    name: "accountcertificatvalueguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "FineAccountGUID",
    name: "fineaccountguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "DiscountAccountGUID",
    name: "discountaccountguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "TaxAccount",
    name: "taxaccount",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "OtherFeeAccount1GUID",
    name: "otherfeeaccount1guid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "OtherFeeAccount2GUID",
    name: "otherfeeaccount2guid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "OtherFeeAccount3GUID",
    name: "otherfeeaccount3guid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "OtherFeeAccount4GUID",
    name: "otherfeeaccount4guid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "OtherFeeAccount5GUID",
    name: "otherfeeaccount5guid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "InsuranceAccountGuid",
    name: "insuranceaccountguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "ServesComm",
    name: "servescomm",
    type: "number",
  },
  {
    required: false,
    label: "Rentcondition",
    name: "rentcondition",
    type: "text",
  },
  {
    required: false,
    label: "MoveCost",
    name: "movecost",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostCredit",
    name: "movecostcredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "DefPrintPath",
    name: "defprintpath",
    type: "text",
  },
  {
    required: false,
    label: "DefPrintLogPath",
    name: "defprintlogpath",
    type: "text",
  },
  {
    required: false,
    label: "CreateEntry",
    name: "createentry",
    type: "checkbox",
  },
  {
    required: false,
    label: "AutoCreateEntry",
    name: "autocreateentry",
    type: "checkbox",
  },
  {
    required: false,
    label: "AutoPostedEntry",
    name: "autopostedentry",
    type: "checkbox",
  },
  {
    required: false,
    label: "EntryDate",
    name: "entrydate",
    type: "number",
  },
  {
    required: false,
    label: "MoveCostWithIncom",
    name: "movecostwithincom",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithInsurance",
    name: "movecostwithinsurance",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithContractPrice",
    name: "movecostwithcontractprice",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithCertificat",
    name: "movecostwithcertificat",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithFee",
    name: "movecostwithfee",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithclientComm",
    name: "movecostwithclientcomm",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithOwnerComm",
    name: "movecostwithownercomm",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithInconEndContract",
    name: "movecostwithinconendcontract",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithFineEndContract",
    name: "movecostwithfineendcontract",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithIncomCredit",
    name: "movecostwithincomcredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithInsuranceCredit",
    name: "movecostwithinsurancecredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithContractPriceCredit",
    name: "movecostwithcontractpricecredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithCertificatCredit",
    name: "movecostwithcertificatcredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithFeeCredit",
    name: "movecostwithfeecredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithclientCommCredit",
    name: "movecostwithclientcommcredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithOwnerCommCredit",
    name: "movecostwithownercommcredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithInconEndContractCredit",
    name: "movecostwithinconendcontractcredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithFineEndContractCredit",
    name: "movecostwithfineendcontractcredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithDiscount",
    name: "movecostwithdiscount",
    type: "checkbox",
  },
  {
    required: false,
    label: "MoveCostWithDiscountCredit",
    name: "movecostwithdiscountcredit",
    type: "checkbox",
  },
  {
    required: false,
    label: "DefSmsMobile",
    name: "defsmsmobile",
    type: "text",
  },
  {
    required: false,
    label: "AutoSMSAfterAdd",
    name: "autosmsafteradd",
    type: "checkbox",
  },
  {
    required: false,
    label: "SMSMsg",
    name: "smsmsg",
    type: "text",
  },
  {
    required: false,
    label: "SMSMsgEn",
    name: "smsmsgen",
    type: "text",
  },
  {
    required: false,
    label: "AutoSMSAfterEnd",
    name: "autosmsafterend",
    type: "checkbox",
  },
  {
    required: false,
    label: "EndSMSMsg",
    name: "endsmsmsg",
    type: "text",
  },
  {
    required: false,
    label: "EndSMSMsgEn",
    name: "endsmsmsgen",
    type: "text",
  },
  {
    required: false,
    label: "EndContract",
    name: "endcontract",
    type: "checkbox",
  },
  {
    required: false,
    label: "ConstraintInsurance",
    name: "constraintinsurance",
    type: "checkbox",
  },
  {
    required: false,
    label: "DefPrintReceipt",
    name: "defprintreceipt",
    type: "text",
  },
  {
    required: false,
    label: "DefPrintacquittance",
    name: "defprintacquittance",
    type: "text",
  },
  {
    required: false,
    label: "DeflawsuitDebitAccountGUID",
    name: "deflawsuitdebitaccountguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "DeflawsuitCreditAccountGUID",
    name: "deflawsuitcreditaccountguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "LawsuitCustAccount",
    name: "lawsuitcustaccount",
    type: "checkbox",
  },
  {
    required: false,
    label: "LawsuitCostwithDebitAccount",
    name: "lawsuitcostwithdebitaccount",
    type: "checkbox",
  },
  {
    required: false,
    label: "LawsuitCostwithCreditAccount",
    name: "lawsuitcostwithcreditaccount",
    type: "checkbox",
  },
  {
    required: false,
    label: "LawsuitLinkUser",
    name: "lawsuitlinkuser",
    type: "checkbox",
  },
  {
    required: false,
    label: "LawsuitLinkUserExpense",
    name: "lawsuitlinkuserexpense",
    type: "checkbox",
  },
  {
    required: false,
    label: "UnearnedrRevenue",
    name: "unearnedrrevenue",
    type: "checkbox",
  },
  {
    required: false,
    label: "AcIncomNextYearGUID",
    name: "acincomnextyearguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "AcCommissionExpenseGuid",
    name: "accommissionexpenseguid",
    key: "unique",
    keyLabel: "name",
    keyValue: "Guid",
    table: "Account",
  },
  {
    required: false,
    label: "OpNewContract",
    name: "opnewcontract",
    type: "text",
  },
  {
    required: false,
    label: "FirstPayNote",
    name: "firstpaynote",
    type: "text",
  },
  {
    required: false,
    label: "FirstPayNoteLtn",
    name: "firstpaynoteltn",
    type: "text",
  },
  {
    required: false,
    label: "ContractNote",
    name: "contractnote",
    type: "text",
  },
  {
    required: false,
    label: "ContractNoteLtn",
    name: "contractnoteltn",
    type: "text",
  },
  {
    required: false,
    label: "FeeEntryNote",
    name: "feeentrynote",
    type: "text",
  },
  {
    required: false,
    label: "CanBeginDateAfterDate2",
    name: "canbegindateafterdate2",
    type: "checkbox",
  },
  {
    required: false,
    label: "GenEntryEnd",
    name: "genentryend",
    type: "checkbox",
  },
  {
    required: false,
    label: "DefPicTab",
    name: "defpictab",
    type: "text",
  },
];
