export const FlatBuildingDetails = [

  {
    name: "Color",
    type: "color",
    label: "Color",
    required: false,
  },
  {
    name: "Count",
    type: "number",
    label: "Count",
    required: false,
  },
  {
    name: "FlatKind",
    type: "text",
    label: "FlatKind",
    required: false,
  },
  {
    name: "Type",
    type: "text",
    label: "Type",
    required: false,
  },
  {
    name: "Class",
    type: "text",
    label: "Class",
    required: false,
  },
  {
    name: "Area",
    type: "number",
    label: "Area",
    required: false,
  },
  {
    name: "Unity",
    type: "text",
    label: "Unity",
    required: false,
  },
  {
    name: "Rent",
    type: "number",
    label: "Rent",
    required: false,
  },
  {
    name: "CostPrice",
    type: "number",
    label: "CostPrice",
    required: false,
  },
  {
    name: "SalePrice",
    type: "number",
    label: "SalePrice",
    required: false,
  },
  {
    name: "SalePrice2",
    type: "number",
    label: "SalePrice2",
    required: false,
  },
  {
    name: "SalePrice3",
    type: "number",
    label: "SalePrice3",
    required: false,
  },
  {
    name: "FlatOwner",
    type: "number",
    label: "FlatOwner",
    required: false,
  },
  {
    table: "Customer",
    name: "CustGuid",
    key: "unique",
    label: "CustGuid",
    list: [],
  },
  {
    name: "Details",
    type: "text",
    label: "Details",
    required: false,
  },
  {
    name: "Overlooking",
    type: "text",
    label: "Overlooking",
    required: false,
  },
  {
    name: "OfferType",
    type: "number",
    label: "OfferType",
    required: false,
  },
  {
    name: "Restrained",
    type: "number",
    label: "Restrained",
    required: false,
  },
  {
    name: "BathroomCount",
    type: "number",
    label: "BathroomCount",
    required: false,
  },
  {
    name: "BalconyCount",
    type: "number",
    label: "BalconyCount",
    required: false,
  },
  {
    name: "Note",
    type: "text",
    label: "Note",
    required: false,
  },
];
