export const testentry = [
  {
    table: "account",
    key: "unique",
    name: "AcGuid",
    label: "AcGuid",
    required: true,
    list: [],
    keyLabel: "name",
    keyValue: "id",
  },
  {
    type: "number",
    name: "Debit",
    label: "Debit",
    required: true,
  },
  {
    type: "number",
    name: "Credit",
    label: "Credit",
    required: true,
  },
  {
    type: "number",
    name: "Debit",
    label: "Debit",
    required: true,
  },
  {
    table: "Currency",
    key: "unique",
    name: "CurrencyGuid",
    label: "CurrencyGuid",
    required: true,
    list: [],
    keyLabel: "name",
    keyValue: "id",
  },
  {
    type: "number",
    name: "CurrencyVal",
    label: "CurrencyVal",
    required: true,
  },
  {
    type: "text",
    name: "Note",
    label: "Note",
    required: true,
  },
  {
    table: "cost",
    key: "unique",
    name: "CostGuid",
    label: "CostGuid",
    required: true,
    list: [],
    keyLabel: "name",
    keyValue: "id",
  },
  {
    table: "",
    key: "unique",
    name: "ObverseAcGuid",
    label: "ObverseAcGuid",
    required: true,
    list: [],
    keyLabel: "name",
    keyValue: "id",
  },
];
